//USer Address Action
export const FETCH_USER_ADDRESS = 'FETCH_USER_ADDRESS';
export const FETCH_USER_ADDRESS_SUCCESS = 'FETCH_USER_ADDRESS_SUCCESS';
export const FETCH_USER_ADDRESS_FAIL = 'FETCH_USER_ADDRESS_FAIL';

export const ADD_USER_ADDRESS = 'ADD_USER_ADDRESS';
export const ADD_USER_ADDRESS_SUCCESS = 'ADD_USER_ADDRESS_SUCCESS';
export const ADD_USER_ADDRESS_FAIL = 'ADD_USER_ADDRESS_FAIL';
